// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace InventoryProgram.Data
{
    public partial class Inventory
    {
        public int Id { get; set; }
        public string ModelName { get; set; }
        public string SerialNumber { get; set; }
        public string HostName { get; set; }
        public string IpAddress { get; set; }
        public string Category { get; set; }
        public string Owner { get; set; }
        public string Location { get; set; }
    }
}